### ISSUE TITLE
Username protection problem

### ISSUE THREAD

**Issue by cendarlerouge** [jaszhix/NoMansConnect#155]
**Description of the problem:**
I recently re-installed a new Windows 10 on my computer. I wanted to play a little bit with No Man's Sky and your wonderful app so I re-installed it. It says my username is protected by another player (see screenshot attached). I think I protected my username with my old install. When I click either button, it does nothing. (No mail received, and impossible to enter a recovery token) Can you help me to recover my username to protect it again ? It's the same as my Steam account and I'd like the two to match.

Screenshot:
![Capture](https://user-images.githubusercontent.com/16260463/78454266-49e36500-7697-11ea-9f0c-c90a2c2a4627.PNG)

**Windows version**
Windows 10 pro 64bit
**NMC version**
1.10.1
**Absolute path to your storage_x.hg files.**
C:\Users\*myuser*\AppData\Roaming\HelloGames\NMS
**Absolute path to your NMS install directory.**
D:\Jeux Steam\steamapps\common\No Man's Sky

Use Pastebin of directly attach these files (Users/<Username>/AppData/Roaming/NoMansConnect):

**NMC.log**
https://pastebin.com/UecxK5B1
**settings.json**
https://pastebin.com/QDjU2rT1

**Comment by jaszhix** [comment]
I unprotected the username on the server. Will keep this open until the email functionality is fixed.

**Comment by cendarlerouge** [comment]
Thank you very much, sir!

**Comment by Deanosim** [comment]
I'm having the same problem sadly.

**Comment by skainets** [comment]
> 
> 
> I unprotected the username on the server. Will keep this open until the email functionality is fixed.
Need to open a new problem? or can you correct me too? I just reinstalled it and after a while I downloaded it again, installed it and writes about protection. will you help?
Nick Uroboros

**Comment by jaszhix** [comment]
@Deanosim @skainets Disabled protection on both of your profiles.

**Comment by skainets** [comment]
> 
> 
> @Deanosim @skainets Disabled protection on both of your profiles.


Many thanks! And what needs to be done to register correctly ??

**Comment by jaszhix** [comment]
Until the email functionality is fixed, I would keep protection disabled, unless you're not planning on reinstalling the app on another Windows installation.

**Comment by PleaseCarryMe** [comment]
Sorry to bother you but is it possible you could disable protection for my profile PleaseCarryMe. I reinstall windows so often, won't enable it again in the future.

**Comment by jaszhix** [comment]
@PleaseCarryMe Doesn't look like your profile is protected. If it's still a problem, attach your log and I'll take a look.

**Comment by scaryred24** [comment]
I have also encountered the same problem. I had recently built a new PC and switched everything onto there. Username is **scaryred24** encase you wanted to know.

**Comment by jaszhix** [comment]
@scaryred24 Should be fixed for you now.

**Comment by Pontiac76** [comment]
Seems I'm stuck again.  My motherboard died, and I had to reload.  This time, the log files are showing an error 404, and not much else, and only when I go to protect the account.

![image](https://user-images.githubusercontent.com/4532020/93284330-6afcc580-f7a0-11ea-9511-ce5a1c5662c0.png)

**Comment by PleaseCarryMe** [comment]
This is still a problem for me now that im trying to play again for origins update. Dissapointing. I cant even get the pop up to recover with email. just "You must disable username protection to override" and no i do not have it enabled for a second username.

**Comment by jaszhix** [comment]
@PleaseCarryMe Can you attach your NMS log file? It's probably looking up the wrong profile

**Comment by ajsalminen** [comment]
@jaszhix I have a similar problem. Installed on new system, it gave me some new account name that I don't recognize (Dargiukunes) and trying to override to my original one tells me "You must disable username protection before changing your username", override to other random names works fine. Going back to my other no man's connect install, the protection already was set to "X" which I assume is the same as disabled. I can't seem to enable username protection on either of these No Man's Connect installs either, the dialog opens but clicking the "Protect username" doesn't do anything. The username I'm trying to use is "sluxi".

**Comment by jaszhix** [comment]
@ajsalminen I checked the server and can't find a username with "Dargiukunes". Can you attach your NMC log file please? Thanks.

**Comment by ajsalminen** [comment]
Thanks for the reply! The name not being there might be because I had set it to a different one in the end when testing things ("duranburan") if that matters.

I attached a log. I should mention this one is after I copied over NMC's appdata folder from the old system. Hopefully it's still helpful

[nmc.log](https://github.com/jaszhix/NoMansConnect/files/5760837/nmc.log)

**Comment by sgisk** [comment]
I want to play after long time and I have similar problem. I changed some hardware and reinstalled windows and now I can't continue with my profile. I think I copied all data from old installation, but it's not working (maybe because of changed device_id_salt, idk).
Can you disable protection for "peter.sugarek"?

**Comment by Alav74** [comment]
Hello, i have the same problem with username Kartam.
Thanks
[NMC.log](https://github.com/jaszhix/NoMansConnect/files/6345894/NMC.log)
