### ISSUE TITLE
Map crushes to one corner

### ISSUE THREAD

**Issue by ukmerlin** [jaszhix/NoMansConnect#28]
- Connect will suddenly crush the map to one corner of its window so it cannot be used.
- Windows 10 pro
- C:\Users\Steve\AppData\Roaming\HelloGames.
- D:\Program Files (x86)\Steam1\steamapps\common\No Man's Sky.
No particular action triggers it. Once it has happened it will continue to start up like that. 
Image attached.
![nmsconnectcrushesmap](https://user-images.githubusercontent.com/27774213/27755016-52c619b2-5dbb-11e7-97cd-1649c07df19f.jpg)

**Comment by ukmerlin** [comment]
Would suggest a link in the NMC menu to this forum.

**Comment by jaszhix** [comment]
This is caused when someone uploads junk coordinates. I just deleted some and will verify this is corrected. In the mean time delete your remote locations (which will definitely help).

**Comment by jaszhix** [comment]
This should be fixed. NMC will do a once a week cleaning of the cache.json file for dud coordinates causing this (the server has some checks in place too).

**Comment by ukmerlin** [comment]
Sorry to report that this still happens. Had filter PC only set. Cleared it by clearing cache and restarting.

**Comment by jaszhix** [comment]
Some of the locations in your cache may not still be on the server.
